### ISSUE TITLE
is this engine able to match the orders in the right way?

### ISSUE THREAD

**Issue by githubcyc** [ProofSuite/amp-matching-engine#10]
Hi, i'm study matching engine recently, so i wonder if this engine is available to production.

btw, is there any `open-source` project about  **`matching engine`** ?

thanks for ur reply .💕

**Comment by Dvisacker** [comment]
Hi Albert!

This matching-engine is currently in heavy development and is not production ready. It's a matching-engine for decentralized exchanges but with a robust architecture inspired from centralized exchanges. 

Although it is still quite early, this project is indeed open-source and we welcome contributions from people who are interested in the project. I'm sure it's a great to learn about matching-engines :). Feel free to drop me a message anytime at david@proofsuite.com in case you are interested. 

Cheers

**Comment by taalhach** [comment]
Hi!!
How orders are being stored in redis what is structure of queue that contains orders of same price ?
let say 
Price : Order
101   : order1, order2, order3
102   : order1, order2, order3 
in both price orders: order1, order2, order3 are different but grouped with same price

**Comment by piavgh** [comment]
@Dvisacker : Hi, do you guys have the development roadmap for this repository? I mean which part is done | in development | not yet started?
I can see that the actual order matching is not implemented?

The code base is quite big and it's not easy to read the code and figure out this information.
Thanks.
